# Generated by Django 4.1.1 on 2022-10-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_event_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'active']},
        ),
        migrations.AddField(
            model_name='event',
            name='form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_num_partp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('is_member', models.BooleanField(default=False)),
                ('event', models.ManyToManyField(to='Posts.event')),
            ],
        ),
    ]
