# Generated by Django 4.1.1 on 2022-10-02 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_event_options_event_form_event_max_num_partp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
