# Generated by Django 4.1.1 on 2022-10-03 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_eventparticipant_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
    ]
