# Generated by Django 4.1.1 on 2022-09-23 20:42

import Members.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('picture_profile', models.ImageField(blank=True, default='anonymous_user.png', null=True, upload_to=Members.models.member_directory_path_profile)),
                ('dni', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.CharField(choices=[('Comida', 'Comida'), ('Medicamentos', 'Medicamentos'), ('Animales', 'Animales'), ('Otro', 'Otro'), ('Nada', 'Nada')], default='Nada', max_length=15)),
                ('allergies_description', models.CharField(blank=True, max_length=500, null=True)),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('No lo sé', 'No lo sé')], default='No lo sé', max_length=10)),
                ('chronic_disease', models.CharField(blank=True, max_length=500, null=True)),
                ('disease_history', models.CharField(blank=True, max_length=500, null=True)),
                ('treatment_history', models.CharField(blank=True, max_length=500, null=True)),
                ('current_medications', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.CharField(blank=True, max_length=800, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.member')),
            ],
        ),
    ]
