# Generated by Django 4.1.1 on 2022-09-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Members.member'),
        ),
    ]
