# Generated by Django 4.1.1 on 2022-09-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_alter_medicaldata_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='allergies',
            field=models.BooleanField(default=False),
        ),
    ]
