# Generated by Django 4.1.1 on 2022-09-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_alter_medicaldata_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='allergies',
            field=models.BooleanField(choices=[('Comida', 'Comida'), ('Medicamentos', 'Medicamentos'), ('Animales', 'Animales'), ('Otro', 'Otro'), ('Nada', 'Nada')], default=False),
        ),
    ]
