# Generated by Django 4.1.1 on 2022-10-03 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0006_alter_member_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preschool', models.BooleanField(default=False)),
                ('primary', models.BooleanField(default=False)),
                ('secondary', models.BooleanField(default=False)),
                ('technical', models.BooleanField(default=False)),
                ('technology', models.BooleanField(default=False)),
                ('bachelors_degree', models.BooleanField(default=False)),
                ('postgraduate', models.BooleanField(default=False)),
                ('doctorate', models.BooleanField(default=False)),
                ('postdoc', models.BooleanField(default=False)),
                ('in_process', models.BooleanField(default=False)),
                ('culminated', models.BooleanField(default=False)),
                ('paralyzed', models.BooleanField(default=False)),
                ('aspiration', models.TextField(blank=True, max_length=500, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Members.member')),
            ],
        ),
    ]
