# Generated by Django 4.1.1 on 2022-10-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0008_remove_academicdata_culminated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdata',
            name='level',
            field=models.CharField(choices=[('in_process', 'En proceso'), ('culminated', 'Culminado'), ('paralyzed', 'Paralizado')], max_length=50),
        ),
    ]
