# Generated by Django 4.1.1 on 2022-10-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0009_alter_academicdata_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdata',
            name='bachelors_degree',
        ),
        migrations.RemoveField(
            model_name='academicdata',
            name='doctorate',
        ),
        migrations.RemoveField(
            model_name='academicdata',
            name='postdoc',
        ),
        migrations.RemoveField(
            model_name='academicdata',
            name='postgraduate',
        ),
        migrations.RemoveField(
            model_name='academicdata',
            name='preschool',
        ),
        migrations.RemoveField(
            model_name='academicdata',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='academicdata',
            name='secondary',
        ),
        migrations.RemoveField(
            model_name='academicdata',
            name='technical',
        ),
        migrations.RemoveField(
            model_name='academicdata',
            name='technology',
        ),
        migrations.AddField(
            model_name='academicdata',
            name='status',
            field=models.CharField(choices=[('in_process', 'En proceso'), ('culminated', 'Culminado'), ('paralyzed', 'Paralizado')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicdata',
            name='level',
            field=models.CharField(choices=[('preschool', 'Preescolar'), ('primary', 'Primaria'), ('secondary', 'Secundaria'), ('technical', 'Técnico'), ('technology', 'Tecnología'), ('bachelors_degree', 'Licenciatura'), ('postgraduate', 'Posgrado'), ('doctorate', 'Doctorado'), ('postdoc', 'Postdoctorado')], max_length=100),
        ),
    ]
